# Generated by Django 5.0.6 on 2024-09-21 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_alter_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='date_of_incorporation',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
