# Generated by Django 5.0.6 on 2024-09-22 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_alter_company_date_of_incorporation'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_verified',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
