# Generated by Django 5.0.4 on 2024-08-19 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_remove_captable_email_remove_captable_linkedin_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='profuctsandservices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('launch_date', models.DateField()),
                ('description', models.TextField()),
                ('industry', models.CharField(max_length=100)),
                ('type_of_business', models.CharField(max_length=100)),
                ('problem_solved', models.TextField()),
                ('current_year_revenue', models.IntegerField()),
                ('previous_year_revenue', models.IntegerField()),
                ('a_year_befor_revenue', models.IntegerField()),
                ('current_year_pl', models.IntegerField()),
                ('previous_year_pl', models.IntegerField()),
                ('a_year_befor_pl', models.IntegerField()),
                ('customers', models.TextField()),
                ('competitors', models.TextField()),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.company')),
            ],
        ),
    ]
