# Generated by Django 5.0.4 on 2024-08-19 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_profuctsandservices'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='profuctsandservices',
            new_name='productsandservices',
        ),
    ]
