# Generated by Django 5.0.6 on 2024-08-23 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_rename_a_year_befor_pl_productsandservices_a_year_before_pl_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashflow',
            name='beginning_cash_position',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='cashflow',
            name='capital_expenditure',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='cashflow',
            name='cash_flow_from_continuing_financing_activities',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='cashflow',
            name='cash_flow_from_continuing_investing_activities',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='cashflow',
            name='change_in_current_debt_and_capital_lease_obligation',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='cashflow',
            name='change_in_current_deferred_liabilities',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='cashflow',
            name='change_in_hedging_assets_current',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='cashflow',
            name='change_in_inventory',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='cashflow',
            name='change_in_other_current_assets',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='cashflow',
            name='change_in_other_current_liabilities',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='cashflow',
            name='change_in_payables_and_accrued_expense',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='cashflow',
            name='change_in_pension_and_other_post_retirement_benefit_plans_current',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='cashflow',
            name='change_in_working_capital',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='cashflow',
            name='changes_in_cash',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='cashflow',
            name='changes_in_receivables',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='cashflow',
            name='common_stock_dividend_paid',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='cashflow',
            name='common_stock_issuance_payments',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='cashflow',
            name='depreciation_and_amortization',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='cashflow',
            name='end_cash_position',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='cashflow',
            name='financing_cash_flow',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='cashflow',
            name='free_cash_flow',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='cashflow',
            name='goodwill_and_other_intangible_assets',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='cashflow',
            name='investing_cash_flow',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='cashflow',
            name='investments_and_advances',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='cashflow',
            name='issuance_repurchase_of_capital_stock',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='cashflow',
            name='long_term_debt_and_capital_lease_obligation',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='cashflow',
            name='net_income_from_continuing_operations',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='cashflow',
            name='net_ppe_purchase_and_sale',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='cashflow',
            name='non_current_deferred_liabilities',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='cashflow',
            name='operating_cash_flow',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='cashflow',
            name='other_non_current_assets',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='cashflow',
            name='other_non_current_liabilities',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='cashflow',
            name='repayment_of_debt',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='cashflow',
            name='trade_and_other_payables_non_current',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
