# Generated by Django 5.0.6 on 2024-08-24 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_alter_balancesheet_accounts_payable_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='balancesheet',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='cashflow',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='incomestatement',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='balancesheet',
            name='accounts_payable',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='balancesheet',
            name='accounts_receivable',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='balancesheet',
            name='accumulated_depreciation',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='balancesheet',
            name='allowance_for_doubtful_accounts_receivable',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='balancesheet',
            name='buildings_and_improvements',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='balancesheet',
            name='capital_lease_obligation',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='balancesheet',
            name='capital_stock',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='balancesheet',
            name='cash',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='balancesheet',
            name='cash_and_cash_equivalents',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='balancesheet',
            name='cash_cash_equivalents_and_short_term_investments',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='balancesheet',
            name='cash_equivalents',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='balancesheet',
            name='common_stock',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='balancesheet',
            name='current_assets',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='balancesheet',
            name='current_debt',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='balancesheet',
            name='current_debt_and_capital_lease_obligation',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='balancesheet',
            name='current_deferred_liabilities',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='balancesheet',
            name='current_deferred_revenue',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='balancesheet',
            name='current_liabilities',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='balancesheet',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='balancesheet',
            name='finished_goods',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='balancesheet',
            name='gains_or_losses_not_affecting_retained_earnings',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='balancesheet',
            name='goodwill',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='balancesheet',
            name='goodwill_and_other_intangible_assets',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='balancesheet',
            name='gross_accounts_receivable',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='balancesheet',
            name='gross_ppe',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='balancesheet',
            name='hedging_current_assets',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='balancesheet',
            name='income_tax_payable',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='balancesheet',
            name='inventory',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='balancesheet',
            name='investments_and_advances',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='balancesheet',
            name='land_and_improvements',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='balancesheet',
            name='leases',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='balancesheet',
            name='long_term_capital_lease_obligation',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='balancesheet',
            name='long_term_debt',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='balancesheet',
            name='long_term_debt_and_capital_lease_obligation',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='balancesheet',
            name='long_term_equity_investment',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='balancesheet',
            name='machinery_furniture_equipment',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='balancesheet',
            name='net_ppe',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='balancesheet',
            name='non_current_deferred_liabilities',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='balancesheet',
            name='non_current_deferred_revenue',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='balancesheet',
            name='non_current_deferred_taxes_liabilities',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='balancesheet',
            name='other_current_assets',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='balancesheet',
            name='other_current_liabilities',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='balancesheet',
            name='other_equity_adjustments',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='balancesheet',
            name='other_intangible_assets',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='balancesheet',
            name='other_non_current_assets',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='balancesheet',
            name='other_non_current_liabilities',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='balancesheet',
            name='other_properties',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='balancesheet',
            name='other_receivables',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='balancesheet',
            name='other_short_term_investments',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='balancesheet',
            name='payables_and_accrued_expenses',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='balancesheet',
            name='pension_and_other_post_retirement_benefit_plans_current',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='balancesheet',
            name='raw_materials',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='balancesheet',
            name='receivables',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='balancesheet',
            name='retained_earnings',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='balancesheet',
            name='stockholders_equity',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='balancesheet',
            name='total_assets',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='balancesheet',
            name='total_equity_gross_minority_interest',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='balancesheet',
            name='total_liabilities_net_minority_interest',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='balancesheet',
            name='total_non_current_assets',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='balancesheet',
            name='total_non_current_liabilities_net_minority_interest',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='balancesheet',
            name='trade_and_other_payables_non_current',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='balancesheet',
            name='work_in_process',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='cashflow',
            name='beginning_cash_position',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='cashflow',
            name='capital_expenditure',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='cashflow',
            name='cash_flow_from_continuing_financing_activities',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='cashflow',
            name='cash_flow_from_continuing_investing_activities',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='cashflow',
            name='change_in_current_debt_and_capital_lease_obligation',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='cashflow',
            name='change_in_current_deferred_liabilities',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='cashflow',
            name='change_in_hedging_assets_current',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='cashflow',
            name='change_in_inventory',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='cashflow',
            name='change_in_other_current_assets',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='cashflow',
            name='change_in_other_current_liabilities',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='cashflow',
            name='change_in_payables_and_accrued_expense',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='cashflow',
            name='change_in_pension_and_other_post_retirement_benefit_plans_current',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='cashflow',
            name='change_in_working_capital',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='cashflow',
            name='changes_in_cash',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='cashflow',
            name='changes_in_receivables',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='cashflow',
            name='common_stock_dividend_paid',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='cashflow',
            name='common_stock_issuance_payments',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='cashflow',
            name='creator_id',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='cashflow',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='cashflow',
            name='depreciation_and_amortization',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='cashflow',
            name='end_cash_position',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='cashflow',
            name='financing_cash_flow',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='cashflow',
            name='free_cash_flow',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='cashflow',
            name='goodwill_and_other_intangible_assets',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='cashflow',
            name='investing_cash_flow',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='cashflow',
            name='investments_and_advances',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='cashflow',
            name='issuance_repurchase_of_capital_stock',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='cashflow',
            name='long_term_debt_and_capital_lease_obligation',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='cashflow',
            name='modifier_id',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='cashflow',
            name='net_income_from_continuing_operations',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='cashflow',
            name='net_ppe_purchase_and_sale',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='cashflow',
            name='non_current_deferred_liabilities',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='cashflow',
            name='operating_cash_flow',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='cashflow',
            name='other_non_current_assets',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='cashflow',
            name='other_non_current_liabilities',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='cashflow',
            name='repayment_of_debt',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='cashflow',
            name='trade_and_other_payables_non_current',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='incomestatement',
            name='basic_eps',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='incomestatement',
            name='cost_of_revenue',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='incomestatement',
            name='creator_id',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='incomestatement',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='incomestatement',
            name='depreciation_and_amortization',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='incomestatement',
            name='diluted_eps',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='incomestatement',
            name='ebitda',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='incomestatement',
            name='equity_share_dividends',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='incomestatement',
            name='gain_or_loss_on_sale_of_security',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='incomestatement',
            name='general_and_administrative_expenses',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='incomestatement',
            name='gross_profit',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='incomestatement',
            name='interest_expense_non_operating',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='incomestatement',
            name='interest_income_non_operating',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='incomestatement',
            name='modifier_id',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='incomestatement',
            name='net_income',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='incomestatement',
            name='net_income_to_common_stockholders',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='incomestatement',
            name='net_non_operating_interest_income_expense',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='incomestatement',
            name='no_of_equity_shares',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='incomestatement',
            name='operating_expense',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='incomestatement',
            name='operating_income',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='incomestatement',
            name='operating_revenue',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='incomestatement',
            name='other_income_or_expense',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='incomestatement',
            name='other_non_operating_income_or_expenses',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='incomestatement',
            name='preference_share_dividends',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='incomestatement',
            name='pretax_income',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='incomestatement',
            name='research_and_development_expense',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='incomestatement',
            name='retained_earnings',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='incomestatement',
            name='selling_and_marketing_expense',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='incomestatement',
            name='selling_general_and_administrative_expense',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='incomestatement',
            name='special_income_or_charges',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='incomestatement',
            name='tax_provision',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='incomestatement',
            name='total_revenue',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='incomestatement',
            name='write_off',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
