# Generated by Django 5.0.6 on 2024-08-24 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_balancesheet_end_date_cashflow_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incomestatement',
            name='basic_eps',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, null=True),
        ),
    ]
