# Generated by Django 5.0.6 on 2024-08-30 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_alter_incomestatement_basic_eps'),
    ]

    operations = [
        migrations.CreateModel(
            name='BalanceSheetRatios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_ratio', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('quick_ratio', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('cash_ratio', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('working_capital', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('debt_equity_ratio', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('debt_ratio', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('equity_ratio', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('debt_capital_ratio', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('operating_cash_flow_ratio', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('debt_service_coverage_ratio', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('balancesheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.balancesheet')),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.company')),
            ],
        ),
        migrations.CreateModel(
            name='CashFlowRatios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_ratio', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('quick_ratio', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('cash_ratio', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('working_capital', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('operating_cash_flow_ratio', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('debt_service_coverage_ratio', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('cashflowsheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.cashflow')),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.company')),
            ],
        ),
        migrations.CreateModel(
            name='IncomeStatementRatios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gross_profit_ratio', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('operating_profit_ratio', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('ebitda_margin', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('net_profit_margin', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('earnings_per_share', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('interest_service', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('operating_cash_flow_ratio', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('debt_service_coverage_ratio', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.company')),
                ('incomesheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.incomestatement')),
            ],
        ),
    ]
