# Generated by Django 5.1 on 2024-09-10 06:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0015_balancesheetratios_cashflowratios_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='news',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_date', models.DateField(default=None, null=True)),
                ('line_no', models.IntegerField(default=None, null=True)),
                ('summary', models.TextField()),
                ('link', models.CharField(default=None, max_length=50, null=True)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.company')),
            ],
        ),
        migrations.CreateModel(
            name='plan_finacials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_no', models.IntegerField(default=None, null=True)),
                ('b_plan_pdf', models.FileField(null=True, upload_to='plan_pdf')),
                ('f_plan_pdf', models.FileField(null=True, upload_to='f_plan_pdf')),
                ('p_name', models.CharField(default=None, max_length=50, null=True)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.company')),
            ],
        ),
    ]
