# Generated by Django 5.1 on 2024-09-17 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0017_forecastingcashflow'),
    ]

    operations = [
        migrations.AddField(
            model_name='balancesheet',
            name='month_or_quarter_or_year_name',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='cashflow',
            name='month_or_quarter_or_year_name',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='incomestatement',
            name='month_or_quarter_or_year_name',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
