# Generated by Django 5.0.6 on 2024-09-18 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0021_benchmark_companypptandvideo'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='subscription_type',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
